### ISSUE TITLE
Invalid matrix error

### ISSUE THREAD

**Issue by L0Lock** [L0Lock/convertRotationMode#37]
**System Information**
Operating system: Linux KDE Neon 6.0.2

**Blender Version**
Broken: 4.0.2
addon v 1.3.2

**Short description of error**

```py
##################
### test message devMode
############
# i like my 930
### Working on bone "torso" ###
 # Target Rmode will be YZX
 |  # Backed up and unlocked rotations
 |  # Jumped to frame 181
 |  |  # "torso" Rmode set to YZX
 |  |  # Copied "torso" Global Transform as YZX
 |  |  # Rmnode set to YZX
Traceback (most recent call last):
  File "/home/roikku/.config/blender/4.0/scripts/addons/convert_Rotation_Mode_v1-3-2_for_Blender4-0-0.py", line 188, in execute
    bpy.ops.object.paste_transform(method='CURRENT', use_mirror=False)
  File "/home/roikku/MyApps/Blender/stable/blender-4.0.2+stable.9be62e85b727/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Operator bpy.ops.object.paste_transform.poll() Clipboard does not contain a valid matrix
Error: Python: Traceback (most recent call last):
  File "/home/roikku/.config/blender/4.0/scripts/addons/convert_Rotation_Mode_v1-3-2_for_Blender4-0-0.py", line 188, in execute
    bpy.ops.object.paste_transform(method='CURRENT', use_mirror=False)
  File "/home/roikku/MyApps/Blender/stable/blender-4.0.2+stable.9be62e85b727/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Operator bpy.ops.object.paste_transform.poll() Clipboard does not contain a valid matrix

```

Manually doing the copy-pasting as the addon is meant to perform works correctly.
Hitting the Paste button in Copy Global Transform just after the error doesn't return that error, so i guess the clipboard isn't actually empty/ have a supported matrix?

 
[error_test.zip](https://github.com/L0Lock/convertRotationMode/files/14947262/error_test.zip)

**Comment by L0Lock** [comment]
Can't reproduce on 4.2.0.

**Comment by BlackwellHarper** [comment]
Same error in Blender 4.2.2 LTS
Add-on version 1.4.3

`Python: Traceback (most recent call last):
  File "C:\Users\Kai\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\convert_rotation_mode\operators.py", line 79, in execute
    bpy.ops.object.paste_transform(method='CURRENT', use_mirror=False)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.object.paste_transform.poll() Clipboard does not contain a valid matrix
`
